git:
  disable: true

steps:
  script: echo 1
  script2:
    on:
      branch:
      - main
    run: |
      echo 222  
  script3:
    env:
      - KKK=v
    run: |
      echo $KKK
      echo 6666777
      echo 1111333444888
